[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "cors",
    "serverless-http",
    "@prisma/client",
    "prisma"
  ]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"