export enum ErrorCode {
	EMAIL_IN_USE = 'EMAIL_IN_USE',
	NAME_IN_USE = 'NAME_IN_USE',
	WRONG_EMAIL = 'WRONG_EMAIL',
	COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	INVALID_TOKEN = 'INVALID_TOKEN',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
	IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
	TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
	FORBIDDEN = 'FORBIDDEN',
	INSTAGRAM_ERROR = 'INSTAGRAM_ERROR',
	FILE_TOO_LARGE = 'FILE_TOO_LARGE',
	INVALID_IMAGE = 'INVALID_IMAGE',
	UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
}
